language: android
dist: trusty

android:
  components:
    # The BuildTools version used by the project
    - build-tools-29.0.2

    # The SDK version used to compile the project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
